artifact_location: file:C:/Users/sanap/.gemini/antigravity/scratch/mlops_project/mlruns_xgboost/0
creation_time: 1766480822122
experiment_id: '0'
last_update_time: 1766480822122
lifecycle_stage: active
name: Default
