artifact_uri: file:C:/Users/sanap/.gemini/antigravity/scratch/mlops_project/mlruns_test/804550488051575190/f7d95dfe7a88419f9999851f4fe0bd43/artifacts
end_time: 1766479185605
entry_point_name: ''
experiment_id: '804550488051575190'
lifecycle_stage: active
run_id: f7d95dfe7a88419f9999851f4fe0bd43
run_name: respected-ox-403
source_name: ''
source_type: 4
source_version: ''
start_time: 1766479179921
status: 3
tags: []
user_id: sanap
