artifact_location: file:C:/Users/sanap/.gemini/antigravity/scratch/mlops_project/mlruns_test/0
creation_time: 1766479179537
experiment_id: '0'
last_update_time: 1766479179537
lifecycle_stage: active
name: Default
