artifact_location: file:C:/Users/sanap/.gemini/antigravity/scratch/mlops_project/mlruns_xgboost/695521025052029989
creation_time: 1766480822291
experiment_id: '695521025052029989'
last_update_time: 1766480822291
lifecycle_stage: active
name: CustomerChurnPrediction
