artifact_location: file:C:/Users/sanap/.gemini/antigravity/scratch/mlops_project/mlruns_test/804550488051575190
creation_time: 1766479179573
experiment_id: '804550488051575190'
last_update_time: 1766479179573
lifecycle_stage: active
name: CustomerChurnPrediction
